[[customizations.filesystem]]
mountpoint = "/"
minsize = "20 GiB"

# This is only for test purposes of the image and will not be in the final iso.
[[customizations.user]]
name = "astrodon"
password = "cosmic-dino"
groups = ["wheel"]
